name: test

on: 
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: gingonic/gin:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Install dependencies
        run: go mod init && go mod tidy

      - name: Run tests
        run: go test ./...
        
      - name: Build the application
        run: go build -o myapp ./cmd/myapp

      - name: Run the application
        run: ./myapp